CREATE INDEX IF NOT EXISTS "cove_v3_events_price_time_idx" ON "cove_v3_events" USING btree ("network","token_id","created_at" DESC NULLS LAST,"block_height" DESC NULLS LAST,"txid" DESC NULLS LAST) WHERE "cove_v3_events"."canonical" and "cove_v3_events"."valid" and "cove_v3_events"."operation" in ('MINT','REDEEM') and "cove_v3_events"."gross_sats" is not null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_events_positive_price_time_idx" ON "cove_v3_events" USING btree ("network","token_id","created_at" DESC NULLS LAST,"block_height" DESC NULLS LAST,"txid" DESC NULLS LAST) WHERE "cove_v3_events"."canonical" and "cove_v3_events"."valid" and "cove_v3_events"."operation" in ('MINT','REDEEM') and "cove_v3_events"."amount_atoms" > 0 and "cove_v3_events"."gross_sats"::numeric * 10000000000000 >= "cove_v3_events"."amount_atoms";--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_market_fills_buyer_token_idx" ON "cove_v3_market_fills" USING btree ("network","buyer_token_script","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_market_fills_buyer_change_idx" ON "cove_v3_market_fills" USING btree ("network","buyer_change_script","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_market_listings_route_idx" ON "cove_v3_market_listings" USING btree ("network","token_id","amount_atoms","total_price_sats","listing_id") WHERE "cove_v3_market_listings"."status" = 'ACTIVE';--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_market_listings_seller_token_idx" ON "cove_v3_market_listings" USING btree ("network","seller_token_script","created_at" DESC NULLS LAST,"listing_id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_market_listings_seller_payout_idx" ON "cove_v3_market_listings" USING btree ("network","seller_payout_script","created_at" DESC NULLS LAST,"listing_id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_market_trades_price_time_idx" ON "cove_v3_market_trades" USING btree ("network","token_id","created_at" DESC NULLS LAST,"block_height" DESC NULLS LAST,"txid" DESC NULLS LAST) WHERE "cove_v3_market_trades"."canonical";--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_market_trades_positive_price_time_idx" ON "cove_v3_market_trades" USING btree ("network","token_id","created_at" DESC NULLS LAST,"block_height" DESC NULLS LAST,"txid" DESC NULLS LAST) WHERE "cove_v3_market_trades"."canonical" and "cove_v3_market_trades"."amount_atoms" > 0 and "cove_v3_market_trades"."total_price_sats"::numeric * 10000000000000 >= "cove_v3_market_trades"."amount_atoms";--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cove_v3_utxo_live_script_idx" ON "cove_v3_token_utxos" USING btree ("network","script_pub_key","txid","vout") WHERE "cove_v3_token_utxos"."canonical" and "cove_v3_token_utxos"."spent_by_txid" is null;