import { expect, test, vi } from "vitest";
import * as bitcoin from "bitcoinjs-lib";
import * as core from "@crclaunch/crc20-protocol";
import { ECPairFactory } from "ecpair";
import * as ecc from "tiny-secp256k1";
import { makeCrcSellerListing, signCrcSellerListing } from "./crc-market-seller";
import { authorizeOffer } from "../../../../packages/cove-market/crc20-protocol/test-support/signing.js";
const key = ECPairFactory(ecc).fromPrivateKey(Buffer.alloc(32, 2));
const payment = bitcoin.payments.p2wpkh({ pubkey: key.publicKey, network: bitcoin.networks.regtest });
const script = payment.output!.toString("hex");
const input = { txid: "aa".repeat(32), vout: 0, atoms: 1n, sats: 1000n, scriptHex: script, deployTxid: "bb".repeat(32) };
const config = { network: "regtest", ticker: "TEST", vaultScriptHex: `0014${"11".repeat(20)}`, creatorScriptHex: script, protocolScriptHex: `0014${"22".repeat(20)}` };
const state: core.Asset = { config, deployTxid: input.deployTxid, issuedAtoms: 10000000000n, inventoryAtoms: 0n, burnedAtoms: 0n, vault: { txid: "cc".repeat(32), vout: 0, sats: 1003n, scriptHex: config.vaultScriptHex } };
const options = { network: "regtest", tokenCoin: { ...input, atoms: "1" }, bitcoinCoin: { txid: input.txid, vout: 0, valueSats: "1000" }, coreState: core.encodeProtocolDto(state), sellerScriptHex: script, publicKeyHex: key.publicKey.toString("hex"), priceSats: 5000n, currentHeight: 100, expiryHeight: 112 };
test("projects arbitrary atom offers and uses core 83 + BIP322 wallet authorization", async () => {
  const listing = makeCrcSellerListing(options);
  expect(listing.amountAtoms).toBe(1n);
  expect(listing.protocolFeeSats).toBe(core.marketFee(5000n));
  const fixture = await authorizeOffer({ network: "regtest", deployTxid: input.deployTxid, ticker: "TEST", listedInput: input, sellerScriptHex: script, priceSats: 5000n, expiryHeight: 112 }, key.privateKey!);
  const signer = vi.fn(async (base64: string, operation: string) => { expect(operation).toBe("P2P_LIST"); const p = bitcoin.Psbt.fromBase64(base64); p.signInput(0, key, [131]); return p.toBase64(); });
  const message = vi.fn(async (text: string) => { expect(text).toBe(core.offerMessage(fixture)); return Buffer.from(fixture.signatureHex, "hex").toString("base64"); });
  const offer = await signCrcSellerListing(listing, { address: payment.address!, publicKey: key.publicKey.toString("hex") }, signer, message);
  expect(core.offerMessage(offer)).toBe(core.offerMessage(fixture));
  expect(() => core.verifyOffer(offer)).not.toThrow();
  expect(signer).toHaveBeenCalledOnce(); expect(message).toHaveBeenCalledOnce();
});
test("rejects wrong ownership, missing carrier and expiry before wallet authorization", () => {
  expect(() => makeCrcSellerListing({ ...options, bitcoinCoin: null })).toThrow();
  expect(() => makeCrcSellerListing({ ...options, expiryHeight: 100 })).toThrow();
  expect(() => makeCrcSellerListing({ ...options, sellerScriptHex: config.protocolScriptHex })).toThrow();
  expect(() => makeCrcSellerListing({ ...options, publicKeyHex: "02" + "ff".repeat(32) })).toThrow();
});
